[workspace]
members = ["crates/mcp-recon-core", "crates/mcp-recon-cli"]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/euanmcrosson-dotcom/mcp-recon"
authors = ["Euan McRosson <euanmcrosson@gmail.com>"]

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
