/**
 * Markdown reporter — render an inventory + classification (+ optional
 * fuzz) into a single Markdown threat profile a security reviewer
 * actually reads.
 *
 * The output structure:
 *
 *   1. Heading + generated-at + server identity
 *   2. Summary stats (counts, distributions, headline finding)
 *   3. Per-tool sections, ordered by authority (privileged →
 *      destructive → write → read), with the recommended caveat in
 *      a copy-pasteable code block
 *   4. Footer linking back to capnagent / mcp-recon docs
 */

import type {
	AuthorityLevel,
	Classification,
	ClassificationResults,
	DataClass,
} from "../classify/types.js";
import type { ToolInventory } from "../enumerate.js";
import type { FuzzResults } from "../fuzz/types.js";

const AUTHORITY_ORDER: Record<AuthorityLevel, number> = {
	privileged: 0,
	destructive: 1,
	write: 2,
	read: 3,
};

export interface RenderInput {
	inventory: ToolInventory;
	classification: ClassificationResults;
	fuzz?: FuzzResults;
}

/** Render a Markdown threat profile. Pure function — no I/O. */
export function renderMarkdown(input: RenderInput): string {
	const { inventory, classification, fuzz } = input;
	const out: string[] = [];

	const serverLabel = `${inventory.server.name ?? "(unnamed server)"} v${inventory.server.version ?? "?"}`;

	out.push(`# Threat profile: ${serverLabel}`);
	out.push("");
	out.push(
		`> Generated by [mcp-recon](https://github.com/euanmcrosson-dotcom/mcp-recon) at ${classification.scanned_at}.`,
	);
	out.push(
		"> Companion to [capnagent](https://github.com/euanmcrosson-dotcom/capnagent) — every recommended caveat below is a copy-pasteable capnagent predicate.",
	);
	out.push("");

	// ─── Summary ─────────────────────────────────────────────────
	out.push("## Summary");
	out.push("");

	const byClass = countBy(classification.classifications, (c) => c.data_class);
	const byAuthority = countBy(
		classification.classifications,
		(c) => c.authority_level,
	);
	const cdpCount = classification.classifications.filter(
		(c) => c.confused_deputy_candidate,
	).length;
	const total = classification.classifications.length;

	out.push(`- **Tools:** ${total}`);
	out.push(`- **Data-class distribution:** ${formatDistribution(byClass)}`);
	out.push(
		`- **Authority-level distribution:** ${formatDistribution(byAuthority)}`,
	);
	out.push(
		`- **Confused-deputy candidates:** ${cdpCount} / ${total}${cdpCount === 0 ? " ✅" : ""}`,
	);

	if (fuzz) {
		const fOk = fuzz.summary.reduce((acc, s) => acc + s.ok, 0);
		const fProto = fuzz.summary.reduce((acc, s) => acc + s.protocol_error, 0);
		const fRuntime = fuzz.summary.reduce((acc, s) => acc + s.runtime_error, 0);
		const fTotal = fOk + fProto + fRuntime;
		out.push(
			`- **Fuzz:** ${fTotal} calls — ok=${fOk}, protocol_error=${fProto}, runtime_error=${fRuntime}${fRuntime > 0 ? "  ⚠️ at least one input escaped protocol-error handling" : ""}`,
		);
	}
	out.push("");

	// ─── Per-tool sections ───────────────────────────────────────
	out.push("## Tools");
	out.push("");

	const fuzzByTool = new Map<string, ReturnType<typeof toolFuzzSummary>>();
	if (fuzz) {
		for (const s of fuzz.summary) {
			fuzzByTool.set(s.tool, toolFuzzSummary(s));
		}
	}

	// Sort by authority (privileged first), then by data-class, then by name.
	const sortedClassifications = [...classification.classifications].sort(
		(a, b) => {
			const ord =
				AUTHORITY_ORDER[a.authority_level] - AUTHORITY_ORDER[b.authority_level];
			if (ord !== 0) return ord;
			if (a.data_class !== b.data_class)
				return a.data_class.localeCompare(b.data_class);
			return a.tool.localeCompare(b.tool);
		},
	);

	for (const c of sortedClassifications) {
		const tool = inventory.tools.find((t) => t.name === c.tool);
		out.push(...renderTool(c, tool?.description ?? "", fuzzByTool.get(c.tool)));
		out.push("");
	}

	// ─── Footer ──────────────────────────────────────────────────
	out.push("---");
	out.push("");
	out.push("## How to read this report");
	out.push("");
	out.push(
		"Every classification has a `confidence` score (noisy-OR over fired rules — see [docs/METHODOLOGY.md](https://github.com/euanmcrosson-dotcom/mcp-recon/blob/master/docs/METHODOLOGY.md)) and a free-form `rationale` listing every rule that fired. If you disagree with a classification:",
	);
	out.push("");
	out.push(
		"1. Read the `rationale` — which rules fired, and which you'd reweight.",
	);
	out.push(
		"2. Edit `crates/mcp-recon-core/src/rules/v0_1.rs` (rule weights) or `packages/mcp-recon-cli/src/classify/rules.ts` (TS mirror) and re-run.",
	);
	out.push("3. Open an issue with your reasoning so future runs benefit.");
	out.push("");
	out.push(
		"**Recommended caveats are starting points, not finish lines.** Tighten the placeholders to match your deployment, and consider attaching additional caveats (caller binding, time-of-day windows, rate limits enforced upstream).",
	);
	out.push("");

	return out.join("\n");
}

function renderTool(
	c: Classification,
	description: string,
	fuzzStats?: ReturnType<typeof toolFuzzSummary>,
): string[] {
	const out: string[] = [];

	const cdp = c.confused_deputy_candidate ? " ⚠️ confused-deputy candidate" : "";
	out.push(`### ${c.tool}`);
	out.push("");
	out.push(
		`**Class:** \`${c.data_class}\` · **Authority:** \`${c.authority_level}\`${cdp} · **Confidence:** ${(c.confidence * 100).toFixed(1)}%`,
	);

	if (description) {
		const trimmed =
			description.length > 320 ? `${description.slice(0, 320)}…` : description;
		out.push("");
		out.push(`**Description:** ${trimmed.replace(/\s+/g, " ")}`);
	}

	out.push("");
	out.push(`**Rationale:** ${c.rationale}`);

	if (fuzzStats) {
		out.push("");
		out.push(
			`**Fuzz:** ${fuzzStats.total} calls — ok=${fuzzStats.ok}, protocol_error=${fuzzStats.protocol_error}, runtime_error=${fuzzStats.runtime_error}${fuzzStats.runtime_error > 0 ? "  ⚠️" : ""}`,
		);
	}

	out.push("");
	out.push("**Recommended capnagent caveat:**");
	out.push("");
	out.push("```");
	out.push(c.recommended_caveat);
	out.push("```");

	return out;
}

function countBy<T>(
	items: readonly T[],
	key: (t: T) => string,
): Record<string, number> {
	const out: Record<string, number> = {};
	for (const item of items) {
		const k = key(item);
		out[k] = (out[k] ?? 0) + 1;
	}
	return out;
}

function formatDistribution(d: Record<string, number>): string {
	const entries = Object.entries(d).sort((a, b) => b[1] - a[1]);
	return entries.map(([k, v]) => `${k} (${v})`).join(", ") || "(none)";
}

function toolFuzzSummary(s: FuzzResults["summary"][number]): {
	total: number;
	ok: number;
	protocol_error: number;
	runtime_error: number;
} {
	return {
		total: s.total,
		ok: s.ok,
		protocol_error: s.protocol_error,
		runtime_error: s.runtime_error,
	};
}
