/**
 * Markdown renderer for the v0.1 caveats document.
 *
 * Where `report.renderMarkdown` turns an inventory + classification
 * into a security-reviewer threat profile, this module turns a
 * caveats document into an **operator-facing issuance plan**:
 *
 *   1. Heading + generated-at + server identity
 *   2. Bindings block — caller / sandbox prefix / expiry, with an
 *      explicit `<unbound>` marker for any binding the operator
 *      didn't supply (so the review pass is loud about gaps).
 *   3. Summary stats (total / ready / flagged)
 *   4. ⚠ Flagged plans — each with classification, flag-reason
 *      bullets, the caveats in a fenced code block, and the
 *      preserved `// comment` if present.
 *   5. Plans ready to issue — same shape minus flag reasons.
 *
 * Sections without entries are omitted entirely so a 100%-ready run
 * doesn't print an empty "Flagged" heading and a 100%-flagged dry
 * run doesn't print an empty "Ready" heading.
 */

import type { CaveatPlan, CaveatsResults } from "./types.js";

/** Render a Markdown issuance plan. Pure function — no I/O. */
export function renderCaveatsMarkdown(results: CaveatsResults): string {
  const out: string[] = [];

  const serverLabel = `${results.server.name ?? "(unnamed server)"} v${results.server.version ?? "?"}`;

  out.push("# capnagent issuance plan");
  out.push("");
  out.push(`> Generated by [mcp-recon](https://github.com/euanmcrosson-dotcom/mcp-recon) at ${results.scanned_at}.`);
  out.push(`> Source server: **${serverLabel}**`);
  out.push("");

  // Bindings block — shows operator inputs verbatim, with explicit
  // `<unbound>` for any missing field (matching the JSON document's
  // "review pass" semantics).
  out.push("## Bindings");
  out.push("");
  out.push(`- **caller:** ${formatBinding(results.bindings.caller)}`);
  out.push(`- **sandbox_prefix:** ${formatBinding(results.bindings.sandbox_prefix)}`);
  out.push(`- **expiry:** ${formatBinding(results.bindings.expiry)}`);
  out.push("");

  // Summary
  out.push("## Summary");
  out.push("");
  out.push(`- **Total plans:** ${results.summary.total}`);
  out.push(`- **Ready to issue:** ${results.summary.ready}`);
  out.push(`- **Flagged for review:** ${results.summary.flagged}`);
  out.push("");

  const flaggedPlans = results.plans.filter((p) => p.flagged);
  const readyPlans = results.plans.filter((p) => !p.flagged);

  if (flaggedPlans.length > 0) {
    out.push("## ⚠ Flagged plans (review before issuing)");
    out.push("");
    for (const plan of flaggedPlans) {
      out.push(...renderPlan(plan, /* showFlagReasons */ true));
      out.push("");
    }
  }

  if (readyPlans.length > 0) {
    out.push("## Plans ready to issue");
    out.push("");
    for (const plan of readyPlans) {
      out.push(...renderPlan(plan, /* showFlagReasons */ false));
      out.push("");
    }
  }

  return out.join("\n");
}

function renderPlan(plan: CaveatPlan, showFlagReasons: boolean): string[] {
  const out: string[] = [];

  const cdc = plan.confused_deputy_candidate ? " · ⚠️ confused-deputy candidate" : "";
  out.push(`### ${plan.tool}`);
  out.push("");
  out.push(`**Class:** \`${plan.data_class}\` · **Authority:** \`${plan.authority_level}\`${cdc}`);
  out.push("");
  out.push(`**Purpose:** \`${plan.purpose}\``);

  if (showFlagReasons && plan.flag_reasons.length > 0) {
    out.push("");
    out.push(`**Flag reasons:**`);
    out.push("");
    for (const reason of plan.flag_reasons) {
      out.push(`- \`${reason}\``);
    }
  }

  out.push("");
  out.push(`**Caveats:**`);
  out.push("");
  out.push("```");
  for (const c of plan.caveats) {
    out.push(c);
  }
  out.push("```");

  if (plan.comment !== undefined) {
    out.push("");
    out.push(`**Comment:** ${plan.comment}`);
  }

  return out;
}

function formatBinding(value: string | undefined): string {
  return value === undefined ? "`<unbound>`" : `\`${value}\``;
}
